// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd-2ep63U1llld2qVXGBdYgbb_JJj7Wws',
    appId: '1:102219512141:web:f1558b6ec6e6ffb8e5df04',
    messagingSenderId: '102219512141',
    projectId: 'etl-project-bd7fa',
    authDomain: 'etl-project-bd7fa.firebaseapp.com',
    storageBucket: 'etl-project-bd7fa.firebasestorage.app',
    measurementId: 'G-3P5K5YHXHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQgjRACjKzAfKPhqhyaoU4ZXERTsZZDO4',
    appId: '1:102219512141:android:a0c6afb0fde5c330e5df04',
    messagingSenderId: '102219512141',
    projectId: 'etl-project-bd7fa',
    storageBucket: 'etl-project-bd7fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARjlHSzhx_uESQFYLKG27RVD3OZyCh2-k',
    appId: '1:102219512141:ios:f58acfb6c2f731fae5df04',
    messagingSenderId: '102219512141',
    projectId: 'etl-project-bd7fa',
    storageBucket: 'etl-project-bd7fa.firebasestorage.app',
    iosBundleId: 'com.example.etlApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARjlHSzhx_uESQFYLKG27RVD3OZyCh2-k',
    appId: '1:102219512141:ios:f58acfb6c2f731fae5df04',
    messagingSenderId: '102219512141',
    projectId: 'etl-project-bd7fa',
    storageBucket: 'etl-project-bd7fa.firebasestorage.app',
    iosBundleId: 'com.example.etlApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd-2ep63U1llld2qVXGBdYgbb_JJj7Wws',
    appId: '1:102219512141:web:c28a45260ce723f3e5df04',
    messagingSenderId: '102219512141',
    projectId: 'etl-project-bd7fa',
    authDomain: 'etl-project-bd7fa.firebaseapp.com',
    storageBucket: 'etl-project-bd7fa.firebasestorage.app',
    measurementId: 'G-KZYD45HL1C',
  );
}
